booking/api/urls.py
from django.urls import path

from . import views
from . import game
from . import booking
from . import event

app_name = "api"
urlpatterns = [
    path("material", views.export_material, name="material"),
    path("materialalias", views.export_materialalias, name="materialalias"),
    path("game/new", game.edit_game, name="new_game"),
    path("game/edit/<int:game_id>", game.edit_game, name="edit_game"),
    path("game/delete/<int:game_id>", game.delete_game, name="delete_game"),
    path(
        "game/edit/<int:game_id>/move/<str:direction>",
        game.move_game,
        name="move_game",
    ),
    path("booking/new", booking.edit_booking, name="new_booking"),
    path("booking/edit/<int:booking_id>", booking.edit_booking, name="edit_booking"),
    path(
        "booking/delete/<int:booking_id>", booking.delete_booking, name="delete_booking"
    ),
    path(
        "event/<slug:event_slug>/<slug:group_slug>/xlsx",
        event.EventExcelView.as_view(),
        name="excel_event",
    ),
]

booking/urls.py
from django.urls import path, include

from .views import EventGameView, EventListView, HomeView

app_name = "booking"
urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("<slug:event_slug>", EventGameView.as_view(), name="event_display"),
    path("<slug:event_slug>/games", EventGameView.as_view(), name="event_games"),
    path(
        "<slug:event_slug>/games/<slug:group_slug>",
        EventGameView.as_view(),
        name="event_games_group",
    ),
    path("<slug:event_slug>/list", EventListView.as_view(), name="event_list"),
    path(
        "<slug:event_slug>/list/<slug:group_slug>",
        EventListView.as_view(),
        name="event_list_group",
    ),
    path("api/", include("booking.api.urls")),
]

catalog/urls.py
from django.urls import path

from .views import MaterialDetailView, MaterialDetailModalView, MaterialListView

app_name = "catalog"
urlpatterns = [
    path("<int:pk>", MaterialDetailView.as_view(), name="material"),
    path("<int:pk>/modal", MaterialDetailModalView.as_view(), name="material_modal"),
    path("", MaterialListView.as_view(), name="catalog"),
]

dbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from booking.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("booking/", include("booking.urls")),
    path("catalog/", include("catalog.urls")),
    path("users/", include("users.urls")),
    path("camera/", include("camera.urls")),
    path("admin/", admin.site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(domain="djangojs", packages=["booking"]),
        name="javascript-catalog",
    ),
]
# The following patterns only work if DEBUG = TRUE. Django should not be used for
#  serving static files or uploaded files in production environments.
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

booking/models/material.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models
from django.db.models.functions import Lower
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.fields import TreeManyToManyField

from booking.models import Category, Location, RateClass


def format_stock_value(val: float) -> str:
    """
    Removes trailing zeroes and after that any trailing dot.
    """
    return "{:.2f}".format(val).rstrip("0").rstrip(".")


class Material(models.Model):
    name = models.CharField(verbose_name=_("name"), max_length=150, unique=True)
    description = RichTextField(
        verbose_name=_("description"),
        blank=True,
        config_name="basic_ckeditor",
        help_text=_(
            "Additional information about the material. Displayed in the shop."
        ),
    )
    categories = TreeManyToManyField(
        Category, related_name="materials", verbose_name=_("categories")
    )
    gm = models.BooleanField(
        verbose_name=_("GM"), help_text=_("Is GM needed for this material?")
    )
    lendable = models.BooleanField(
        verbose_name=_("lendable"),
        default=False,
        help_text=_("Should this material be shown for lending?"),
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_("location"),
        help_text=_("Where can this material be found?"),
        related_name="materials",
    )
    rate_class = models.ForeignKey(
        RateClass,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_("rate class"),
        related_name="materials",
        help_text=_("What rate class should this material be associated with?"),
    )
    stock_value = models.FloatField(
        verbose_name=_("stock value"),
        null=True,
        blank=True,
        help_text=_("How many exemplars are there of this material?"),
    )
    lendable_stock_value = models.FloatField(
        verbose_name=_("lendable stock value"),
        null=True,
        blank=True,
        help_text=_("How many exemplars of this materials are lendable?"),
    )
    stock_unit = models.CharField(
        verbose_name=_("stock unit"),
        max_length=150,
        blank=True,
        help_text=_("Specify a unit for the stock. E.g. meters."),
    )
    last_modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name = _("material")
        verbose_name_plural = _("materials")
        get_latest_by = "last_modified"
        ordering = [Lower("name")]

    def __str__(self):
        return self.name

    @property
    def stock(self):
        """
        Returns a human readable representation of the stock
        """
        parts = []
        if self.stock_value is not None:
            parts.append(format_stock_value(self.stock_value))
        if len(parts) and self.stock_unit:
            parts.append(self.stock_unit)
        return " ".join(parts).strip()

    stock.fget.short_description = _("stock")

    @property
    def lendable_stock(self):
        """
        Returns a human readable representation of the lendable stock
        """
        parts = []
        if self.lendable_stock_value is not None:
            parts.append(format_stock_value(self.lendable_stock_value))
        elif self.stock_value:
            parts.append(format_stock_value(self.stock_value))
        if len(parts) and self.stock_unit:
            parts.append(self.stock_unit)
        return " ".join(parts).strip()

    lendable_stock.fget.short_description = _("lendable stock")

    @property
    def sku(self):
        return self.id + settings.SHOP_SKU_OFFSET

    @staticmethod
    def last_modification():
        try:
            return Material.objects.latest().last_modified
        except Material.DoesNotExist:
            return None

    def get_absolute_url(self):
        return reverse("catalog:material", kwargs={"pk": self.pk})

    def get_shop_url(self):
        if self.lendable and settings.SHOP_PRODUCT_URL_FORMAT:
            return settings.SHOP_PRODUCT_URL_FORMAT.format(sku=self.sku)
        else:
            return None

booking/models/material_alias.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from booking.models import Material


class MaterialAlias(models.Model):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=150,
        unique=True,
        help_text=_(
            'Alias for the material, e.g. aliases for "stormbaan" are "Kelly" and '
            '"Rambler".'
        ),
    )
    material = models.ForeignKey(
        Material,
        on_delete=models.CASCADE,
        verbose_name=_("material"),
        related_name="aliases",
    )

    class Meta:
        verbose_name = _("material alias")
        verbose_name_plural = _("material aliases")

    def __str__(self):
        return self.name

booking/api/views.py
from django.http import HttpResponseBadRequest

from booking.api import material, materialalias
from booking.models import Material, MaterialAlias


def export_material(request):
    materials = Material.objects.prefetch_related(
        "categories", "images", "attachments", "rate_class", "aliases"
    ).all()
    export_format = request.GET.get("format", "json")
    if export_format == "woocommerce":
        return material.format_woocommerce(request, materials)
    elif export_format == "json":
        return material.format_json(request, materials)
    else:
        return HttpResponseBadRequest("Unknown format")


def export_materialalias(request):
    material_aliases = MaterialAlias.objects.all()
    export_format = request.GET.get("format", "json")
    if export_format == "json":
        return materialalias.format_json(request, material_aliases)
    else:
        return HttpResponseBadRequest("Unknown format")

booking/views/GroupPermissionError.py
class GroupPermissionError(PermissionError):
    pass

booking/views/event_game_view.py
from django.shortcuts import redirect

from booking.forms import GameForm
from booking.models import Game, PartOfDay
from booking.views import EventView


class EventGameView(EventView):
    template_name = "booking/event/game-view.html"

    def dispatch(self, request, *args, **kwargs):
        """Redirect to the list view if all groups are requested"""
        group_slug = kwargs.get("group_slug", None)
        if (
            group_slug is None
            and request.user.is_authenticated
            and request.user.group is None
        ):
            # If the user is not in a group and did not supply a group, show all groups
            group_slug = "all"
        if group_slug == "all":
            # There is no game view for all groups
            return redirect("booking:event_list_group", kwargs.get("event_slug"), "all")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_event = context["current_event"]

        # Get the games per day and part of day
        games = {
            day: {
                part_of_day: Game.objects.filter(
                    event=current_event,
                    day=day,
                    part_of_day=part_of_day,
                    **self.get_group_filter(context["current_group"])
                )
                for part_of_day, _ in PartOfDay.PART_OF_DAY_CHOICES
            }
            for day in current_event.days
        }

        # TODO Are the game_forms really necessary?
        game_forms = {
            day: GameForm(
                initial={
                    "event": current_event,
                    "day": day,
                    **self.get_group_filter(context["current_group"]),
                },
                auto_id="id_game_%s_" + str(day.isoformat()),
            )
            for day in current_event.days
        }

        context.update(
            {
                "game_forms": game_forms,
                "games": games,
            }
        )

        return context

booking/views/event_list_view.py
from booking.filters import BookingFilter
from booking.models import Booking, PartOfDay
from booking.models.list_view_filter import ListView
from booking.views import EventView


class EventListView(EventView):
    template_name = "booking/event/list-view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get the bookings for this event and group, also apply filter from UI
        current_event = context["current_event"]
        bookings = BookingFilter(
            self.request.GET,
            request=self.request,
            queryset=Booking.objects.prefetch_related(
                "material",
                "material__categories",
                "game",
                "game__group",
            ).filter(
                game__event=current_event,
                **self.get_group_filter(context["current_group"], "game__")
            ),
        )

        # Arrange the bookings in lists using the ListViewFilters per day and part of
        #  day
        list_views = {
            day: {
                part_of_day: ListView().get_lists(
                    bookings.qs.filter(
                        game__day=day,
                        game__part_of_day=part_of_day,
                    ),
                )
                for part_of_day, _ in PartOfDay.PART_OF_DAY_CHOICES
            }
            for day in current_event.days
        }

        context.update({"list_views": list_views, "filter": bookings})

        return context

booking/views/event_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView

from booking.mixins import BookingPageMixin
from booking.models import Event
from dbase.user_alert_exception import UserAlertException
from users.group_permission_error import GroupPermissionError
from users.models import Group


class EventView(LoginRequiredMixin, BookingPageMixin, TemplateView):
    template_name = "booking/event/event.html"

    def get_requested_group(self, group_slug):
        """
        Translates a group slug in the request to a Group object or None if group_slug
        is "all". Also verifies whether the user doing the request may view the
        requested group.
        :param str group_slug: "all" | None | Group.slug
        :return Group: Group or None
        :raises UserAlertException: user is not assigned to a group and may not view
         bookings from other groups.
        """
        if group_slug == "all":
            requested_group = None
        elif group_slug is None:
            # No group was requested, so use user's own group, may be None
            requested_group = self.request.user.group
        else:
            requested_group = get_object_or_404(Group, slug=group_slug)

        # Check if user may view this group
        if not self.request.user.has_perm(
            "users.view_bookings_from_group", requested_group
        ):
            raise GroupPermissionError(
                _("You are not allowed to view bookings for this group.")
            )

        return requested_group

    def get_requested_event(self, event_slug):
        event = get_object_or_404(Event, slug=event_slug)
        if not self.request.user.has_perm("booking.view_event", event):
            raise UserAlertException(_("You are not allowed to view this event"))
        return event

    @staticmethod
    def get_group_filter(requested_group, filter_prefix=""):
        """
        Returns a filter dictionary for Games or Bookings that filters the requested
        group. If requested_group is None (all groups), an empty dict is returned, hence
        no filter.
        :param Group requested_group: Group | None
        :param str filter_prefix: prefix for the filter, e.g. game__, to filter groups
         of games of bookings.
        :return: dict
        """
        if requested_group is None:
            return dict()
        return {filter_prefix + "group": requested_group}

    def get_context_data(self, **kwargs):
        """Retrieves the requested event and the requested group"""
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "current_event": self.get_requested_event(
                    self.kwargs.get("event_slug")
                ),
                "current_group": self.get_requested_group(
                    self.kwargs.get("group_slug", None)
                ),
            }
        )
        return context

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except GroupPermissionError as e:
            user_group = self.request.user.group
            if user_group is None:
                # Cannot use own group
                raise UserAlertException(
                    _(
                        "You are not assigned to a group. Please contact a board "
                        "member to resolve this issue."
                    )
                )
            else:
                return redirect(
                    reverse(
                        "booking:event_games_group",
                        kwargs={
                            "event_slug": self.kwargs.get("event_slug"),
                            "group_slug": user_group.slug,
                        },
                    )
                )

booking/views/home_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.utils.translation import gettext_lazy as _
from django.views.generic import View

from booking.models import Event
from dbase.mixins import UserAlertMixin
from dbase.user_alert_exception import UserAlertException


class HomeView(LoginRequiredMixin, UserAlertMixin, View):
    """
    Redirects user to the most recent open event or shows a message that there are no
    open events.
    """

    def get(self, request, *args, **kwargs):
        events = Event.objects.viewable(self.request.user)
        if not events:
            raise UserAlertException(_("There are no open events."))
        return redirect(events.first().get_absolute_url())

booking/templates/booking/partials/booking-item.html
{% load i18n %}
{% load crispy_forms_tags %}
{% load roles %}
{% load rules %}
{% has_perm 'booking.change_booking' user booking as can_edit_booking %}
<tr class="booking d-flex flex-wrap" data-id="{{ booking.pk }}" data-material-name="{{ booking.material.name }}" data-material-id="{{ booking.material.id }}" data-amount="{{ booking.amount }}" data-game-id="{{ booking.game.pk }}" data-stock="{{ booking.material.stock }}">
  <td class="booking-form col-12">
    {% if booking %}
      {% if include_game %}
        {% if include_group %}
          {% crispy booking.form_with_group %}
        {% else %}
          {% crispy booking.form_with_game %}
        {% endif %}
      {% else %}
        {% crispy booking.form %}
      {% endif %}
    {% else %}
      <form></form>
    {% endif %}
  </td>
  <td class="booking-check booking-info d-flex align-items-center col-auto pl-md-3 pl-sm-2">
    <div class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" id="check-booking-{{ booking.pk }}">
      <label class="custom-control-label" for="check-booking-{{ booking.pk }}"></label>
    </div>
  </td>
  <td class="booking-material booking-info col col-md-3">
    {% if booking.material %}
      <a role="button" data-catalog-item="{% url 'catalog:material_modal' booking.material.pk %}" data-toggle="modal" data-target="#catalogModal" class="text-dark booking-name">
        {{ booking }}
      </a>
    {% else %}
    <div class="booking-name">
      {{ booking }}
    </div>
    {% endif %}
    <div class="booking-material-category small text-muted text-truncate">
      {% if booking.material %}
        {{ booking.material.categories.all.0 }}
      {% else %}
        <span title="{% trans "This booking needs review" %}" data-toggle="tooltip" data-placement="right">
          <i class="fas fa-exclamation-triangle text-warning"></i>
          {% trans "Custom material" %}
        </span>
      {% endif %}
    </div>
  </td>
  <td class="booking-amount booking-info d-flex align-items-center col-2 col-md-2">
    {{ booking.amount }}
  </td>
  {% if include_game %}
    {% if include_group %}
      <td class="booking-game-group booking-info col-3 col-md-2" data-group-id="{{ booking.game.group.pk }}">
        <div class="text-truncate" title="{{ booking.game.group.name }}" data-toggle="tooltip" data-placement="left">{{ booking.game.group.name }}</div>
        <div class="booking-game small text-muted">
          <a class="text-truncate" title="{{ booking.game.name }}" data-toggle="tooltip" data-placement="left" href="{% url "booking:event_games_group" booking.game.event.slug booking.game.group.slug %}#game{{ booking.game.pk }}">
            {{ booking.game.name }}
          </a>
        </div>
      </td>
    {% else %}
      <td class="booking-game booking-info d-flex align-items-center col-3 col-md-2">
        <a class="text-truncate" title="{{ booking.game.name }}" data-toggle="tooltip" data-placement="left" href="{% url "booking:event_games_group" booking.game.event.slug booking.game.group.slug %}#game{{ booking.game.pk }}">
          {{ booking.game.name }}
        </a>
      </td>
    {% endif %}
  {% endif %}
  <td class="booking-workweek booking-info d-flex align-items-center justify-content-center col-1 col-md-1">
    {% if booking.workweek %}
      <i class="fas fa-check"></i>
    {% endif %}
    {% if can_edit_booking  %}
    <div class="booking-controls editor text-right position-absolute align-items-center show-xs">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2 d-print-none" role="group" aria-label="{% trans "Booking options" %}">
          <span data-toggle="modal" data-target="#deleteBookingModal" data-action="{% url 'booking:api:delete_booking' booking.id %}" class="delete-booking" data-method="post">
            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" class="btn btn-outline-danger rounded-left" style="border-radius: 0;" title="{% trans "Delete" %}"><i class="far fa-trash-alt"></i></a>
          </span>
          <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" class="btn btn-outline-secondary edit-booking" title="{% trans "Edit" %}"><i class="fas fa-edit"></i></a>
        </div>
      </div>
    </div>
    {% endif %}
  </td>
  {% spaceless %}
  <td class="booking-comment booking-info text-truncate d-flex align-items-center col-md col-12 mt-n2 mt-md-0 small text-muted text-wrap flex-wrap">
    {% if booking.comment %}
      <span data-toggle="tooltip" data-placement="bottom" title="{% trans "Comment" %}">
        <i class="far fa-fw fa-comment text-secondary mr-2 d-md-none"></i>
      </span>
      {{ booking.comment }}
    {% endif %}
    {% if can_edit_booking %}
    <div class="booking-controls editor text-right position-absolute align-items-center show-md">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2 d-print-none" role="group" aria-label="{% trans "Booking options" %}">
          <span data-toggle="modal" data-target="#deleteBookingModal" data-action="{% url 'booking:api:delete_booking' booking.id %}" class="delete-booking" data-method="post">
            <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" class="btn btn-outline-danger rounded-left" style="border-radius: 0;" title="{% trans "Delete" %}"><i class="far fa-trash-alt"></i></a>
          </span>
          <a href="javascript:void(0);" data-toggle="tooltip" data-placement="bottom" class="btn btn-outline-secondary edit-booking" title="{% trans "Edit" %}"><i class="fas fa-edit"></i></a>
        </div>
      </div>
    </div>
    {% endif %}
  </td>
  {% endspaceless %}


  {% if booking.custom_material %}
    {% if perms.booking.add_material or perms.booking.add_materialalias %}
      <td class="booking-admin-controls editor d-none col-12 small text-muted d-md-flex">
        <ul class="list-horizontal">
          {% if perms.booking.add_material %}
            <li><a href="{% url 'admin:booking_material_add' %}?name={{ booking.custom_material }}" class="text-secondary">{% trans "Create new material" %}</a></li>
          {% endif %}
          {% if perms.booking.add_materialalias %}
            <li><a href="{% url 'admin:booking_materialalias_add' %}?name={{ booking.custom_material }}" class="text-secondary">{% trans "Create material alias" %}</a></li>
          {% endif %}
        </ul>
      </td>
    {% endif %}
  {% endif %}

</tr>

booking/templates/booking/partials/day-nav.html
{% load dictionary %}
{% load i18n %}
{% load rules %}
{% has_perm 'booking.add_group_game' user current_group as can_add_game %}
<nav class="col-lg-3 d-none d-lg-block navbar navbar-light bg-light day-nav">
  <div class="sticky-top" style="top: 5rem; z-index: 1019;">
    <a class="navbar-brand" href="#day{{ day.isoformat }}">{{ day|date:"l"|capfirst }}</a>
    <nav class="nav nav-pills flex-column">
      {% for code, trans in parts_of_day %}
        {% if games and games|get_item:code|length %}
          <a class="nav-link active-secondary" href="#{{ day.isoformat }}{{ code }}">{{ trans }}</a>
          <nav class="nav nav-pills flex-column">
            {% for game in games|get_item:code %}
              <a class="nav-link ml-3 my-1" href="#game{{ game.pk }}">{{ game.name }}</a>
            {% endfor %}
          </nav>
        {% endif %}
        {% if list_views and list_views|get_item:code|length %}
          <a class="nav-link active-secondary" href="#{{ day.isoformat }}{{ code }}">{{ trans }}</a>
          <nav class="nav nav-pills flex-column">
          {% for list_view, bookings in list_views|get_item:code %}
            <a class="nav-link ml-3 my-1" href="#list{{ day.isoformat }}{{ code }}{{ list_view.pk }}">{{ list_view.name }}</a>
          {% endfor %}
          </nav>
        {% endif %}
      {% endfor %}
      {% if games %}
        {% if can_add_game  %}
          <a class="btn btn-outline-secondary text-left mt-4 editor" href="#{{ day.isoformat }}new"><i class="fas fa-plus-square"></i> {% trans "Add new game" %}</a>
        {% endif %}
      {% endif %}
    </nav>
  </div>
</nav>

booking/templates/booking/partials/delete-booking-modal.html
{% load i18n %}
<div class="modal fade" id="deleteBookingModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">{% translate "Are you sure?" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% translate "Do you really want to delete the booking <strong class='booking-name'></strong>?" %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger confirm-delete" data-dismiss="modal">{% translate "Remove booking" %}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% translate "Cancel" %}</button>
      </div>
    </div>
  </div>
</div>

booking/templates/booking/partials/delete-game-modal.html
{% load i18n %}
<div class="modal fade" id="deleteGameModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">{% translate "Are you sure?" %}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% translate "Do you really want to delete the game <strong class='game-name'></strong> along with all its bookings?" %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger confirm-delete" data-dismiss="modal">{% translate "Remove game" %}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% translate "Cancel" %}</button>
      </div>
    </div>
  </div>
</div>

booking/templates/booking/partials/list-view-card.html
{% load i18n %}
{% load crispy_forms_tags %}
<div class="card list mb-3" id="list{{ day.isoformat }}{{ part_of_day }}{{ list_view_filter.pk }}" data-part-of-day-code="{{ part_of_day }}" data-day="{{ day.isoformat }}">
  <div class="card-header">
    <div class="list-header row">
      <div class="list-name card-name col-auto py-2">{{ list_view_filter.name }}</div>
    </div>
  </div>
  <div class="card-body p-0 collapse show">
    <div class="table-responsive-md">
      <table class="bookings-table table table-sm table-hover mb-0">
        <thead>
          <tr class="d-flex">
            <th scope="col" class="booking-check check-all text-center col-auto pl-md-3 pl-sm-2">
              <div class="custom-control custom-checkbox" data-toggle="tooltip" data-placement="top" title="{% trans "Set status on all bookings" %}">
                <input type="checkbox" class="custom-control-input" id="check-all-{{ day.isoformat }}{{ part_of_day }}{{ list_view_filter.pk }}">
                <label class="custom-control-label" for="check-all-{{ day.isoformat }}{{ part_of_day }}{{ list_view_filter.pk }}"></label>
              </div>
            </th>
            <th scope="col" class="booking-material col col-md-3">{% trans "Material" %}</th>
            <th scope="col" class="booking-amount col-2 col-md-2 text-truncate" data-toggle="tooltip" title="{% trans "Amount" %}">{% trans "Amount" %}</th>
            <th scope="col" class="booking-game col-3 col-md-2 text-truncate" data-toggle="tooltip" title="{% trans "Game" %}">{% trans "Game" %}</th>
            <th scope="col" class="booking-workweek text-center col-1 col-md-1 text-truncate" data-toggle="tooltip" title="{% trans "Workweek" %}">{% trans "Workweek" %}</th>
            <th scope="col" class="booking-comment d-none d-md-table-cell col">{% trans "Comment" %}</th>
          </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
          {% include "booking/partials/booking-item.html" with booking=booking include_game=True include_group=include_group %}
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

booking/templates/booking/partials/material-detail-modal.html
{% load i18n %}
<div class="modal fade" id="catalogModal" tabindex="-1" aria-labelledby="catalogModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header p-0" style="height: 0">
        <button type="button" class="close mt-3 mr-3" style="z-index: 2000" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body pb-0">
        ...
      </div>
      <div class="modal-footer border-top-0 pt-0">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "Close" %}</button>
      </div>
    </div>
  </div>
</div>