camera/urls.py
from django.urls import path

from camera.views import CameraView, UploadImageView, ListView

app_name = "camera"
urlpatterns = [
    path("", CameraView.as_view(), name="index"),
    path("upload", UploadImageView.as_view(), name="update_image"),
    path("list", ListView.as_view(), name="list"),
]

dbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from booking.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("booking/", include("booking.urls")),
    path("catalog/", include("catalog.urls")),
    path("users/", include("users.urls")),
    path("camera/", include("camera.urls")),
    path("admin/", admin.site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(domain="djangojs", packages=["booking"]),
        name="javascript-catalog",
    ),
]
# The following patterns only work if DEBUG = TRUE. Django should not be used for
#  serving static files or uploaded files in production environments.
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

camera/views.py
import base64
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.files.base import ContentFile
from django.db.models import Count
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views import View

from booking.models import Material, MaterialImage


class CameraView(PermissionRequiredMixin, TemplateView):
    permission_required = "booking.change_material"
    template_name = "camera/camera.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["materials"] = (
            Material.objects.filter()
            .annotate(image_count=Count("images"))
            .order_by(
                "image_count", "lendable", "name"
            )  # Sort materials with images on bottom
        )
        return context


class UploadImageView(PermissionRequiredMixin, View):
    permission_required = "booking.change_material"

    def post(self, request):
        material = Material.objects.get(pk=int(request.POST["material"]))

        _, imgstr = request.POST["image"].split(";base64,")
        image = ContentFile(base64.b64decode(imgstr), name="camera.png")

        material_image = MaterialImage(image=image, material=material).save()
        print(material_image)

        return JsonResponse({"status": "success"})


class ListView(CameraView):
    template_name = "camera/list.html"

camera/templates/camera/camera.html
{% extends "theme/base.html" %}
{% load static %}
{% load i18n %}


{% block content %}
  <div class="position-relative">
    <div class="camera text-center position-relative">
      <video autoplay playsinline class="w-100"></video>
      <button type="button" class="camera-shutter osb btn btn-light rounded-circle border border-secondary">
        <i class="fas fa-camera fa-2x"></i>
      </button>
    </div>
    <canvas id="canvas"></canvas>
    <div class="photo text-center d-none position-relative">
      <img class="w-100" alt="Screen capture" id="photo">
      <button type="button" class="camera-back osb btn btn-light rounded-circle border border-secondary">
        <i class="fas fa-arrow-left fa-2x"></i>
      </button>
      <button type="button" class="camera-save osb btn btn-light rounded-circle border border-secondary">
        <i class="fas fa-save fa-2x"></i>
      </button>
    </div>
    <div class="camera-menu row">
      <div class="col-10 camera-material">
        <h2 class="lead">{% trans "Photograph" %} <strong>{{ materials.0.name }}</strong></h2>
      </div>
      <div class="col-2 camera-skip text-right">
        <button type="button" class="btn btn-outline-secondary">{% trans "Skip" %}</button>
      </div>
    </div>
  </div>

  <div class="list mt-3 container">
    {% include "camera/list.html" with materials=materials %}
  </div>
{% endblock %}


{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static "camera/css/app.min.css" %}">
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static "camera/js/app.min.js" %}" type="text/javascript"></script>
{% endblock %}

camera/templates/camera/list.html
{% load i18n %}
{% load thumbnail %}
<div class="row">
  {% for material in materials %}
    <div class="col-md-6 mb-2 row material-item" data-id="{{ material.pk }}" data-name="{{ material.name }}">
      <div class="col-auto">
        {% if material.images.first %}
          {% thumbnail material.images.first.image "100x100" crop="center" as image %}
            <img src="{{ image.url }}" alt="{{ material.name }}">
          {% endthumbnail %}
        {% else %}
          <img src="https://via.placeholder.com/100x100.png?text={% trans "No+photo" %}" alt="Placeholder">
        {% endif %}
      </div>
      <div class="col">
        <a href="#" class="h-100 d-flex">
          <div class="align-self-center pl-3 text-break">
            {{ material.name }}
            {% if material.lendable %}
              <br><div class="badge badge-secondary">{% trans "lendable" %}</div>
            {% endif %}
          </div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>

camera/templates/camera/material_change_list_camera_button.html
{% extends "admin/change_list.html" %}
{% load i18n %}
{% load static %}

{% block object-tools-items %}
  <li>
    <a href="{% url "camera:index" %}">
      {% translate "Camera" %}
      <i class="fas fa-camera fa-fw"></i>
    </a>
  </li>
  {{ block.super }}
  <script src="{% static "dbase/js/icons.min.js" %}" type="text/javascript"></script>
{% endblock %}