catalog/urls.py
from django.urls import path

from .views import MaterialDetailView, MaterialDetailModalView, MaterialListView

app_name = "catalog"
urlpatterns = [
    path("<int:pk>", MaterialDetailView.as_view(), name="material"),
    path("<int:pk>/modal", MaterialDetailModalView.as_view(), name="material_modal"),
    path("", MaterialListView.as_view(), name="catalog"),
]

dbase/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from booking.views import HomeView

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
    path("booking/", include("booking.urls")),
    path("catalog/", include("catalog.urls")),
    path("users/", include("users.urls")),
    path("camera/", include("camera.urls")),
    path("admin/", admin.site.urls),
    path(
        "jsi18n/",
        JavaScriptCatalog.as_view(domain="djangojs", packages=["booking"]),
        name="javascript-catalog",
    ),
]
# The following patterns only work if DEBUG = TRUE. Django should not be used for
#  serving static files or uploaded files in production environments.
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

booking/models/material.py
from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import models
from django.db.models.functions import Lower
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.fields import TreeManyToManyField

from booking.models import Category, Location, RateClass


def format_stock_value(val: float) -> str:
    """
    Removes trailing zeroes and after that any trailing dot.
    """
    return "{:.2f}".format(val).rstrip("0").rstrip(".")


class Material(models.Model):
    name = models.CharField(verbose_name=_("name"), max_length=150, unique=True)
    description = RichTextField(
        verbose_name=_("description"),
        blank=True,
        config_name="basic_ckeditor",
        help_text=_(
            "Additional information about the material. Displayed in the shop."
        ),
    )
    categories = TreeManyToManyField(
        Category, related_name="materials", verbose_name=_("categories")
    )
    gm = models.BooleanField(
        verbose_name=_("GM"), help_text=_("Is GM needed for this material?")
    )
    lendable = models.BooleanField(
        verbose_name=_("lendable"),
        default=False,
        help_text=_("Should this material be shown for lending?"),
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_("location"),
        help_text=_("Where can this material be found?"),
        related_name="materials",
    )
    rate_class = models.ForeignKey(
        RateClass,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_("rate class"),
        related_name="materials",
        help_text=_("What rate class should this material be associated with?"),
    )
    stock_value = models.FloatField(
        verbose_name=_("stock value"),
        null=True,
        blank=True,
        help_text=_("How many exemplars are there of this material?"),
    )
    lendable_stock_value = models.FloatField(
        verbose_name=_("lendable stock value"),
        null=True,
        blank=True,
        help_text=_("How many exemplars of this materials are lendable?"),
    )
    stock_unit = models.CharField(
        verbose_name=_("stock unit"),
        max_length=150,
        blank=True,
        help_text=_("Specify a unit for the stock. E.g. meters."),
    )
    last_modified = models.DateTimeField(auto_now=True, editable=False)

    class Meta:
        verbose_name = _("material")
        verbose_name_plural = _("materials")
        get_latest_by = "last_modified"
        ordering = [Lower("name")]

    def __str__(self):
        return self.name

    @property
    def stock(self):
        """
        Returns a human readable representation of the stock
        """
        parts = []
        if self.stock_value is not None:
            parts.append(format_stock_value(self.stock_value))
        if len(parts) and self.stock_unit:
            parts.append(self.stock_unit)
        return " ".join(parts).strip()

    stock.fget.short_description = _("stock")

    @property
    def lendable_stock(self):
        """
        Returns a human readable representation of the lendable stock
        """
        parts = []
        if self.lendable_stock_value is not None:
            parts.append(format_stock_value(self.lendable_stock_value))
        elif self.stock_value:
            parts.append(format_stock_value(self.stock_value))
        if len(parts) and self.stock_unit:
            parts.append(self.stock_unit)
        return " ".join(parts).strip()

    lendable_stock.fget.short_description = _("lendable stock")

    @property
    def sku(self):
        return self.id + settings.SHOP_SKU_OFFSET

    @staticmethod
    def last_modification():
        try:
            return Material.objects.latest().last_modified
        except Material.DoesNotExist:
            return None

    def get_absolute_url(self):
        return reverse("catalog:material", kwargs={"pk": self.pk})

    def get_shop_url(self):
        if self.lendable and settings.SHOP_PRODUCT_URL_FORMAT:
            return settings.SHOP_PRODUCT_URL_FORMAT.format(sku=self.sku)
        else:
            return None

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from booking.models import Material


class MaterialDetailView(LoginRequiredMixin, DetailView):

    template_name = "catalog/material_detail.html"
    model = Material

catalog/views/material_detail_modal_view.py
from catalog.views import MaterialDetailView


class MaterialDetailModalView(MaterialDetailView):
    template_name = "catalog/material_card.html"

catalog/views/material_detail_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView

from booking.mixins import NavigationMixin
from booking.models import Material


class MaterialDetailView(LoginRequiredMixin, NavigationMixin, DetailView):
    template_name = "catalog/material_detail.html"
    model = Material
    queryset = model.objects.select_related("location").prefetch_related(
        "aliases", "attachments", "categories", "images"
    )

catalog/views/material_list_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from booking.filters import MaterialCategoryFilter
from booking.mixins import NavigationMixin
from booking.models import Material


def get_pages(context, max_pages=8):
    """
    Limits the number of pages displayed by the paginator to max_pages around the
    current page
    :param dict context: RequestContext
    :param int max_pages: Maximum number of pages to display. Odd numbers are subtracted
     by one due to have an equal amount of numbers on each side of the current page.
     The current page is not part of the maximum.
    :return: range with length maximum 8 + 1 (current page).
    """
    page_no = context.get("page_obj").number
    num_pages = context.get("paginator").num_pages
    max_margin = max_pages // 2

    low = max(page_no - max_margin, 1)
    high = min(page_no + max_margin, num_pages)
    # Compute how many pages are on each side of the current page
    margin_left = page_no - low
    margin_right = high - page_no
    # Add extra pages on a side if the other side is below the maximum.
    high += max_margin - margin_left
    low -= max_margin - margin_right
    # Constrain range to (1, num_pages]
    low = max(low, 1)
    high = min(high, num_pages)
    return range(low, high + 1)


class MaterialListView(LoginRequiredMixin, NavigationMixin, ListView):
    template_name = "catalog/material_list.html"
    model = Material
    paginate_by = 30

    def get_filter(self):
        """
        Returns a filter for filtering the queryset by Category.
        :return FilterSet: MaterialCategoryFilter
        """
        return MaterialCategoryFilter(
            self.request.GET,
            request=self.request,
            queryset=Material.objects.prefetch_related(
                "categories", "images", "attachments"
            ),
            wrapper_class="d-flex justify-content-left flex-wrap mx-n1",
        )

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"filter": self.get_filter(), "pages": get_pages(context)})
        return context

catalog/templates/catalog/material_card.html
{% load i18n %}
{% load thumbnail %}
<div class="card mb-3 material-card">
  <div class="card-header sticky-top frosted">
    <h5 class="card-title">
      {{ object.name|capfirst }}
    </h5>
    <ul class="list-inline category-list mt-n3 mb-1">
      {% for category in object.categories.all %}
        <li class="list-inline-item">
          {% for ancestor in category.get_ancestors %}
            <a href="{{ ancestor.get_absolute_url }}">{{ ancestor }}</a>
            &raquo;
          {% endfor %}
          <a href="{{ category.get_absolute_url }}">
            {{ category }}
          </a>
        </li>
      {% empty %}
        {% translate "No categories" %}
      {% endfor %}
      {% if object.gm %}
        <li class="list-inline-item">
          <span class="badge badge-mb" data-toggle="tooltip" title="{% translate "GM is needed for this material" %}">
            {% translate "GM" %}
          </span>
        </li>
      {% endif %}
    </ul>
  </div>
  {% if object.images.count > 0 %}
    <div id="materialImageCarouselIndicators" class="carousel slide carousel-fade carousel-thumbnails" data-interval="false">
      {% if object.images.count > 1 %}
      <ol class="carousel-indicators">
        {% for image in object.images.all %}
        <li data-target="#materialImageCarouselIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}>
          {% thumbnail image.image "60x60" crop="center" as im %}
            <img src="{{ im.url }}" class="img-fluid" alt="{{ object.name }}">
          {% endthumbnail %}
        </li>
        {% endfor %}
      </ol>
      {% endif %}
      <div class="carousel-inner">
        {% for image in object.images.all %}
          {% thumbnail image.image "600" as im %}
            <div class="carousel-item{% if forloop.first %} active{% endif %}">
              <img src="{{ im.url }}" class="d-block mw-100 mx-auto" style="max-height: 60vh;" alt="{{ object.name }}">
            </div>
          {% endthumbnail %}
        {% endfor %}
      </div>
      {% if object.images.count > 1 %}
        <a class="carousel-control-prev" href="#materialImageCarouselIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">{% translate "Previous" %}</span>
        </a>
        <a class="carousel-control-next" href="#materialImageCarouselIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">{% translate "Next" %}</span>
        </a>
      {% endif %}
    </div>
  {% endif %}
  {% if object.description %}
    <div class="card-body pt-3 border-top">
      <div class="text-muted small">{% translate "Description" %}</div>
      <div class="card-text material-description user-html">{{ object.description|safe }}</div>
    </div>
  {% endif %}
  <ul class="list-group list-group-flush">
    {% if object.location %}
      <li class="list-group-item material-location"><span>{% translate "Location" %}</span> {{ object.location.name }}
      </li>
    {% endif %}
    {% if object.stock_value is not None or object.lendable_stock_value is not None %}
      <li class="list-group-item material-stock">
        <span>{% translate "Maximum stock" %}</span> 
        {% if object.stock_value is not None %}
          {{ object.stock }}
        {% endif %}
        {% if object.lendable_stock_value is not None and object.stock_value is not None %}
          {% blocktranslate with amount=object.lendable_stock count counter=object.lendable_stock_value  %}
          (of which {{ amount }} is lendable)
          {% plural %}
          (of which {{ amount }} are lendable)
          {% endblocktranslate %}
        {% endif %}
        {% if object.lendable_stock_value is not None and object.stock_value is None %}
          {% blocktranslate with amount=object.lendable_stock count counter=object.lendable_stock_value  %}
          {{ amount }} is lendable
          {% plural %}
          {{ amount }} are lendable
          {% endblocktranslate %}
        {% endif %}
      </li>
    {% endif %}
    {% if object.aliases.all %}
      <li class="list-group-item material-aliases"><span>{% translate "Aliases" %}</span> {{ object.aliases.all|join:", " }}</li>
    {% endif %}
    {% if object.attachments.all %}
      <li class="list-group-item material-attachments"><span>{% translate "Attachments" %}</span>
      <ul>
        {% for attachment in object.attachments.all %}
        <li>
          <a href="{{ attachment.attachment.url }}" class="text-body">{{ attachment.description }} ({{ attachment.extension }}, {{ attachment.attachment.size|filesizeformat }})</a>
        </li>
        {% endfor %}
      </ul>
      </li>
    {% endif %}
    {% if object.get_shop_url %}
      <li class="list-group-item">
        <a href="{{ object.get_shop_url }}" target="shop" class="btn btn-outline-secondary">
          <i class="fas fa-shopping-cart"></i>
          {% blocktranslate with object_name=object.name|capfirst %}Show {{ object_name }} in lending shop{% endblocktranslate %}
        </a>
      </li>
    {% endif %}
    {% if perms.booking.change_material %}
      <li class="list-group-item">
        <a href="{% url 'admin:booking_material_change' object.pk %}" target="admin" class="btn btn-outline-secondary">
          <i class="fas fa-edit"></i>
          {% blocktranslate with object_name=object.name|capfirst %}Edit properties for {{ object_name }}{% endblocktranslate %}
        </a>
      </li>
    {% endif %}
  </ul>
</div>

catalog/templates/catalog/material_detail.html
{% extends "theme/base.html" %}
{% load static %}
{% load i18n %}

{% block window_title %}
  {{ object.name|capfirst }} | {% translate "Catalog" %} | {{ block.super }}
{% endblock %}

{% block content %}
  <div class="container p-3">
    {% include "catalog/material_card.html" %}
  </div>
{% endblock %}

{% block scripts %}
  <script src="{% static "catalog/js/app.min.js" %}" type="text/javascript"></script>
{% endblock %}

{% block styles %}
  <link href="{% static "catalog/css/app.min.css" %}" rel="stylesheet">
{% endblock %}

catalog/templates/catalog/material_list.html
{% extends "theme/base.html" %}
{% load static %}
{% load thumbnail %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block window_title %}
  {% trans "Catalog" %} | {{ block.super }}
{% endblock %}

{% block content %}
  <h1 class="h2">{% trans "Material catalog" %}</h1>
  <p class="text-muted">
    {% blocktranslate trimmed count obj_count=paginator.count  %}
    One material
    {% plural %}
    {{ obj_count }} materials
    {% endblocktranslate %}
    {% blocktranslate trimmed count pages_count=paginator.num_pages %}
    on one page
    {% plural %}
    on {{ pages_count }} pages
    {% endblocktranslate %}
  </p>

  <h6 class="mb-0">{% translate "Filter by category" %}</h6>
  <form method="get" class="border-bottom mb-4">
    {% crispy filter.form filter.helper %}
  </form>

  <div class="card-columns catalog-masonry mb-3">
    {% for material in object_list %}
      <div class="card">
        {% if material.images.count > 0 %}
          {% thumbnail material.images.first.image "350" crop="center" as im %}
            <figure class="mb-0" style="max-height: 400px; overflow: hidden;">
            <img src="{{ im.url }}" class="card-img-top" alt="{{ material.name|capfirst }}">
            </figure>
          {% endthumbnail %}
        {% endif %}
        <div class="card-body">
          <h5 class="card-title mb-0">
            <a role="button" data-catalog-item="{% url 'catalog:material_modal' material.pk %}" data-toggle="modal" data-target="#catalogModal" class="stretched-link text-body">
              {{ material.name|capfirst }}
            </a>
          </h5>
          {% if material.description %}
            {% autoescape off %}
            <p class="card-text small text-muted">{{ material.description|striptags|truncatewords:20 }}</p>
            {% endautoescape %}
          {% endif %}
        </div>
      </div>
    {% endfor %}
  </div>

  {% include "catalog/paginator.html" %}
{% endblock %}

{% block scripts %}
  {{ block.super}}
  <script src="{% static "catalog/js/app.min.js" %}" type="text/javascript"></script>
{% endblock %}

{% block styles %}
  {{ block.super }}
  <link href="{% static "catalog/css/app.min.css" %}" rel="stylesheet">
{% endblock %}

catalog/templates/catalog/paginator.html
{% load i18n %}
{% load query_url %}
{% if is_paginated %}
{% with the_pages=pages|default_if_none:paginator.page_range %}
  <nav>
    <ul class="pagination justify-content-center flex-wrap">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% param_replace page=page_obj.previous_page_number %}">{% translate "Previous" %}</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{% translate "Previous" %}</a>
        </li>
      {% endif %}
      {% if not 1 in the_pages %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">1</a></li>
      {% endif %}
      {% if the_pages|first > 2 %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&hellip;</a></li>
      {% endif %}
      {% for i in the_pages %}
        {% if page_obj.number == i %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
          </li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if the_pages|last|add:1 < paginator.num_pages %}
        <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&hellip;</a></li>
      {% endif %}
      {% if not paginator.num_pages in the_pages %}
        <li class="page-item"><a class="page-link" href="?{% param_replace page=paginator.num_pages %}">{{ paginator.num_pages }}</a></li>
      {% endif %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% param_replace page=page_obj.next_page_number %}">{% translate "Next" %}</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1" aria-disabled="true">{% translate "Next" %}</a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endwith %}
{% endif %}